version: '3.3'

services:
  app:
    build: .
    container_name: python_app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./graph_data.json:/app/graph_data.json
    command: ["python", "main.py"]
